# Generated by Django 4.2.7 on 2023-11-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="media", verbose_name="Image")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("text", models.TextField(verbose_name="Text")),
                ("date", models.DateField(verbose_name="Date")),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
            },
        ),
    ]
