# Generated by Django 4.2.7 on 2023-11-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeBG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        upload_to="media", verbose_name="First Background Image"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        upload_to="media", verbose_name="Second Background Image"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        upload_to="media", verbose_name="Third Background Image"
                    ),
                ),
                (
                    "image4",
                    models.ImageField(
                        upload_to="media", verbose_name="Forth Background Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Background",
                "verbose_name_plural": "Home Backgrounds",
            },
        ),
    ]
