# Generated by Django 4.2.7 on 2023-11-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_homebg"),
    ]

    operations = [
        migrations.CreateModel(
            name="OurService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text1", models.TextField(verbose_name="First Text")),
                ("text2", models.TextField(verbose_name="Second Text")),
            ],
            options={
                "verbose_name": "Our Service",
                "verbose_name_plural": "Our Services",
            },
        ),
    ]
