# Generated by Django 4.2.7 on 2023-11-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_ourgallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Contact Us Text: ")),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
            ],
            options={
                "verbose_name": "Contact Us Form",
                "verbose_name_plural": "Contact Us Forms",
            },
        ),
    ]
