# Generated by Django 4.2.7 on 2023-11-09 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_contactus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactus",
            name="text",
        ),
    ]
