# Generated by Django 4.2.7 on 2023-11-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_remove_contactus_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactus",
            name="subject",
        ),
        migrations.AddField(
            model_name="contactus",
            name="email",
            field=models.EmailField(max_length=254, null=True, verbose_name="Email"),
        ),
    ]
