# Generated by Django 4.2.7 on 2023-11-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_contactus_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text1", models.TextField(verbose_name="text1")),
                ("text2", models.TextField(verbose_name="text2")),
                ("text3", models.TextField(verbose_name="text3")),
            ],
            options={
                "verbose_name": "About Us",
                "verbose_name_plural": "About Us",
            },
        ),
    ]
